### ISSUE TITLE
Can't get it to run at all

### ISSUE THREAD

**Issue by MerreM** [knownasilya/ember-toastr#13]
No errors, just this.toast / self.toast undefined. 

ember-cli: 2.11.1
node: 6.10.0
os: linux x64

**Comment by knownasilya** [comment]
Services are lazy, so you need to use `get` to use them.

```js
var toast = this.get('toast');
// use toast
```

**Comment by NullVoxPopuli** [comment]
I have this problem, too. but `this.get('toast')` is undefined (I'm using module unification, though), not sure how much that would play in to things.

**Comment by knownasilya** [comment]
Sounds module unification related, since it's still pre alpha 👍

**Comment by NullVoxPopuli** [comment]
sorta, 
I did manage to get things working by having this for my `resolver.js`

```js
import Resolver from 'ember-resolver/resolvers/fallback';
// import Resolver from 'ember-resolver/resolvers/glimmer-wrapper';

import { merge } from '@ember/polyfills';

import buildResolverConfig from 'ember-resolver/ember-config';
import config from '../config/environment';

let moduleConfig = buildResolverConfig(config.modulePrefix);
/*
 * If your application has custom types and collections, modify moduleConfig here
 * to add support for them.
 */

 merge(moduleConfig.types, {
  config: { definitiveCollection: 'main' },
  locale: { definitiveCollection: 'main'},
  'ember-i18n@config': { definitiveCollection: 'main' },
  'util': { definitiveCollection: 'utils' }
});

moduleConfig.collections.main.types.push('config');

export default Resolver.extend({
  config: moduleConfig
});
```
I have other stuff in here in an attempt to get ember-i18n working... but there is no hope of that atm.
the main thing for ember-toastr was the `config: { definitiveCollection: 'main' }`


both ember, and ember-resolver need to expose a config api so that addons can add to the config in a safe way (the existing way is kind of _intimate_ / hacky.
see: https://github.com/emberjs/ember.js/issues/16373
>  Ember addons need an API that allows them to alter the module unification config (for example https://github.com/ember-cli/ember-resolver/blob/master/mu-trees/addon/ember-config.js) and add their own collections and types. In theory Ember (or the resolver?) would use this same API to add its own types and collections.
